excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ssvenkatesh.github.io
title: Venkat 
email: ssvenkatesh@gmail.com
author: S S Venkatesh
tagline: The Big Bang
description: 
paginate: 5
